SELECT  ID,
        CAST(REPLACE(REPLACE(SUBSTRING(RESOURCE,CHARINDEX('ACCOUNTID', RESOURCE),17),'ACCOUNTID:',''),',','') AS BIGINT) AS ACCOUNTID,
        UPPER(REPLACE(SUBSTRING(RESOURCE,CHARINDEX('USERNAME',RESOURCE),13),'USERNAME:','')) AS USERNAME,
        CAST(REPLACE(REPLACE(SUBSTRING(RESOURCE,CHARINDEX('TYPEFINANCIALSERVICE',RESOURCE),24),',',''),'TYPEFINANCIALSERVICE:','') AS INT) AS TYPEFINANCIALSERVICE,
        CASE
            WHEN CAST(REPLACE(REPLACE(SUBSTRING(RESOURCE,CHARINDEX('TYPEFINANCIALSERVICE',RESOURCE),24),',',''),'TYPEFINANCIALSERVICE:','') AS INT) = 37 THEN 'SEGURO PROTECAO DA SORTE'
            ELSE 'SEGURO ACIDENTES PESSOAIS'
        END AS NAMEFINANCIALSERVICE,
        0 AS ACTIVE,
        1 AS SUCCESS,
        CAST(REPLACE(REPLACE(SUBSTRING(RESOURCE,CHARINDEX('CREATEDAT', RESOURCE),35),',',''),'CREATEDAT:','') AS DATETIME) AS CREATEDAT,
        'APLICATIVO' AS CHANNEL
FROM FBR_API_T_EVENTOSNEGOCIOS
WHERE EXTRA_DATA = 'SERVICOS_FINANCEIROS'
AND REPLACE(REPLACE(SUBSTRING(RESOURCE,CHARINDEX('TYPEFINANCIALSERVICE:',RESOURCE),24),',',''),'TYPEFINANCIALSERVICE:','') in (37,41)
AND REPLACE(SUBSTRING(RESOURCE,CHARINDEX('ACTIVE',RESOURCE),8),'ACTIVE:','') = 0
AND REPLACE(SUBSTRING(RESOURCE,CHARINDEX('CHANNEL', RESOURCE),18),'CHANNEL:','') = 'APLICATIVO'
AND CAST(CREATED_AT AS DATE) >= '2020-12-01'
ORDER BY CREATED_AT