SELECT	[CONTEXT] AS TIPO,
		JSON_VALUE(CAST(REQUESTDATA AS NVARCHAR(MAX)), '$.name') AS DS_NOME,
		JSON_VALUE(CAST(REQUESTDATA AS NVARCHAR(MAX)), '$.email') AS DS_EMAIL,
		JSON_VALUE(CAST(REQUESTDATA AS NVARCHAR(MAX)), '$.cpf') AS DS_CPF,
		JSON_VALUE(CAST(REQUESTDATA AS NVARCHAR(MAX)), '$.establishments[0].cnpj') AS DS_CNPJ,
		CREATEDAT AS DT_EVENTO
FROM LOGGER
WHERE CAST(CONTEXT AS NVARCHAR(MAX)) IN ('passwordforgot', 'passwordreset', 'login')
AND ISJSON(CAST(REQUESTDATA AS NVARCHAR(MAX))) > 0
