SELECT  NAME,
		CREATE_DATE,
		MODIFY_DATE,
		LOGINPROPERTY(NAME, 'DAYSUNTILEXPIRATION') DIASPARAEXPIRAR,
		LOGINPROPERTY(NAME, 'PASSWORDLASTSETTIME') DATAULTIMASENHA,
		LOGINPROPERTY(NAME, 'ISEXPIRED') EXPIRADO,
		LOGINPROPERTY(NAME, 'ISMUSTCHANGE') DEVEALTERAR,
		IS_DISABLED,
		TYPE_DESC,
		DEFAULT_DATABASE_NAME
FROM SYS.SQL_LOGINS
