--	ROLE
SELECT	'[' + DB_NAME(DB_ID()) + ']' AS DBNAME,
		DP1.NAME AS DATABASEROLENAME, 
        ISNULL (DP2.NAME, 'NO MEMBERS') AS DATABASEUSERNAME 
FROM SYS.DATABASE_ROLE_MEMBERS AS DRM 
RIGHT OUTER JOIN SYS.DATABASE_PRINCIPALS AS DP1 ON DRM.ROLE_PRINCIPAL_ID = DP1.PRINCIPAL_ID 
LEFT OUTER JOIN SYS.DATABASE_PRINCIPALS AS DP2 ON DRM.MEMBER_PRINCIPAL_ID = DP2.PRINCIPAL_ID 
WHERE DP1.TYPE = 'R' 
AND DP2.NAME = 'apgoulart'
ORDER BY DP1.NAME;
GO
--	TABELAS
SELECT 	DISTINCT 
        RP.NAME, 
        OBJECTTYPE = RP.TYPE_DESC,
        DB_NAME() AS 'DATABASE',
        PERMISSIONTYPE = PM.CLASS_DESC, 
        PM.PERMISSION_NAME, 
        PM.STATE_DESC, 
        OBJECTTYPE = CASE 
                        WHEN OBJ.TYPE_DESC IS NULL OR OBJ.TYPE_DESC = 'SYSTEM_TABLE' THEN PM.CLASS_DESC 
                        ELSE OBJ.TYPE_DESC 
                        END, 
        [OBJECTNAME] = ISNULL(SS.NAME, OBJECT_NAME(PM.MAJOR_ID)) 
FROM SYS.DATABASE_PRINCIPALS RP 
INNER JOIN SYS.DATABASE_PERMISSIONS PM ON PM.GRANTEE_PRINCIPAL_ID = RP.PRINCIPAL_ID 
LEFT JOIN SYS.SCHEMAS SS ON PM.MAJOR_ID = SS.SCHEMA_ID 
LEFT JOIN SYS.OBJECTS OBJ ON PM.[MAJOR_ID] = OBJ.[OBJECT_ID] 
WHERE  RP.TYPE_DESC = 'SQL_USER' 
AND PM.CLASS_DESC <> 'DATABASE'
AND RP.NAME IN ('apgoulart')
ORDER BY RP.NAME,RP.TYPE_DESC,PM.CLASS_DESC

